### PR TITLE
Fixes #57, adds support for 'partially-correct' class

### LINKED ISSUE #57: Partially correct shows incorrect class
When the user needs to select more than one option on a mcq and they select only one the mcq component marks it as partially correct but the tutor adds the incorrect class while showing the partially correct content. Is there anyway to get the partially correct class in there?

### PR DESCRIPTION
**Pull request by brian-learningpool**
When a question has support for a partially correct answer, a corresponding class is now added to the feedback overlay.

### CODE REVIEW

File: js/adapt-contrib-tutor.js [hunk 1]
```diff
@@ -10,7 +10,19 @@ define([
...
 
         if (view.model.has('_isCorrect')) {
-            alertObject._classes = view.model.get('_isCorrect') ? 'correct' : 'incorrect';
+            // Attach specific classes so that feedback can be styled.
+            if (view.model.get('_isCorrect')) {
+                alertObject._classes = 'correct';
+            } else {
+                if (view.model.has('_isAtLeastOneCorrectSelection')) {
+                    // Partially correct feedback is an option.
+                    alertObject._classes = view.model.has('_isAtLeastOneCorrectSelection')
```
Comment (moloko) [inline js/adapt-contrib-tutor.js]: is this not doing the same thing as the `if' statement on the line above? Did you maybe mean `get` rather than `has` here?

Comment (brian-learningpool) [inline js/adapt-contrib-tutor.js]: I sure did, @moloko.  Thanks for spotting.

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1
