### PR TITLE
Fix: Inline feedback normalisation across course and component config (fixes #87)

### LINKED ISSUE #87: Inline feedback doesn't behave correctly on course-only config
### Subject of the issue
Currently, if a component is set to inline feedback on the component (not on the course object), it will look like this:
image

If set to be inline on the course object only, it will look like this:
image

Behaviour should be normalised.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #87

### Fix
* Ensures inline feedback is displayed identically regardless of configuration origin
1. Feedback button is hidden
2. Inline feedback is always open once displayed (except when the question is reset for a subsequent attempt)

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

File: js/adapt-contrib-tutor.js [hunk 1]
```diff
@@ -9,25 +9,28 @@ class Tutor extends Backbone.Controller {
   initialize() {
     this.listenTo(Adapt, {
       'componentView:postRender': this.onComponentViewPostRender,
-      'questionView:showFeedback': this.onQuestionViewShowFeedback
+      'questionView:showFeedback': this.onQuestionViewShowFeedback,
+      'buttonsView:postRender': this.onButtonsViewPostRender
```
Comment (danielghost) [inline js/adapt-contrib-tutor.js:13]: Previously `buttonsView:postRender` was only listened to when needed rather than listening to all events and returning early. Minor point, but isn't it more efficient to only use this as required instead?

File: js/adapt-contrib-tutor.js [hunk 2]
```diff
@@ -9,25 +9,28 @@ class Tutor extends Backbone.Controller {
...
+    if (!shouldShowFeedback) return;
+    model.setupFeedback();
+    Adapt.trigger('questionView:showFeedback', view);
+  }
+
+  onButtonsViewPostRender(view) {
+    const { model } = view;
     if (!model.isTypeGroup('question')) return;
-    const config = model.get('_tutor');
+    const config = !model.get('_tutor')?._isInherited
```
Comment (danielghost) [inline js/adapt-contrib-tutor.js:28]:
```suggestion
    const config = model.get('_tutor')?._isInherited
```
The behaviour wasn't normalised when `_isInherited` on the component as it was pulling in the wrong config.

**Review by danielghost — CHANGES_REQUESTED** [review]

File: js/adapt-contrib-tutor.js (hunk 1 above)
Comment (oliverfoster) [reply js/adapt-contrib-tutor.js:13]: The cost is so negligible it not worth making the code confusing.

File: js/adapt-contrib-tutor.js (hunk 2 above)
Comment (oliverfoster) [reply js/adapt-contrib-tutor.js]: Have sorted in a slightly better way. Apparently there isn't one truthy or falsey expression which fits, my bad.

File: js/adapt-contrib-tutor.js [hunk 3]
```diff
@@ -9,25 +9,28 @@ class Tutor extends Backbone.Controller {
...
-    }
+    const shouldShowFeedback = (model.get('_canShowFeedback') && model.get('_isSubmitted'));
+    if (!shouldShowFeedback) return;
+    model.setupFeedback();
+    Adapt.trigger('questionView:showFeedback', view);
   }
 
   onButtonsViewPostRender(view) {
+    const { model } = view;
+    const config = (!model.get('_tutor') || model.get('_tutor')?._isInherited === true)
```
Comment (danielghost) [inline js/adapt-contrib-tutor.js:28]:
```suggestion
    const config = (!model.get('_tutor') || (model.get('_tutor')?._isInherited ?? true))
```
If the `_tutor` config is present but empty, or missing `_isInherited` it wasn't defaulting to `_isInherited: true` as per the schema. Unlikely for someone to manually configure it this way, but if attributes are missing I guess they should use defaults instead. Should probably add this default value into [TutorModel](https://github.com/adaptlearning/adapt-contrib-tutor/blob/master/js/TutorModel.js) too.

**Review by danielghost — CHANGES_REQUESTED** [review]

**Review by danielghost — APPROVED** [review]
